# Generated by Django 3.2.8 on 2022-02-13 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Surname', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('Phone', models.CharField(max_length=11)),
                ('Email', models.CharField(max_length=100)),
                ('Vet', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PetName', models.CharField(max_length=20)),
                ('PetAge', models.CharField(max_length=3)),
                ('PetImage', models.ImageField(null=True, upload_to='pets')),
                ('PetType', models.CharField(max_length=20)),
                ('PetExplan', models.TextField()),
                ('PetO', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='userpage.petowner')),
                ('Vet', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
