# Generated by Django 3.2.8 on 2022-02-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='PetImage',
            field=models.ImageField(blank=True, null=True, upload_to='pets'),
        ),
    ]
